// Code generated by protoc-gen-go. DO NOT EDIT.
// source: frr-northbound.proto

package frr

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Supported encodings for YANG instance data.
type Encoding int32

const (
	Encoding_JSON Encoding = 0
	Encoding_XML  Encoding = 1
)

var Encoding_name = map[int32]string{
	0: "JSON",
	1: "XML",
}

var Encoding_value = map[string]int32{
	"JSON": 0,
	"XML":  1,
}

func (x Encoding) String() string {
	return proto.EnumName(Encoding_name, int32(x))
}

func (Encoding) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{0}
}

// Type of elements within the data tree.
type GetRequest_DataType int32

const (
	// All data elements.
	GetRequest_ALL GetRequest_DataType = 0
	// Config elements.
	GetRequest_CONFIG GetRequest_DataType = 1
	// State elements.
	GetRequest_STATE GetRequest_DataType = 2
)

var GetRequest_DataType_name = map[int32]string{
	0: "ALL",
	1: "CONFIG",
	2: "STATE",
}

var GetRequest_DataType_value = map[string]int32{
	"ALL":    0,
	"CONFIG": 1,
	"STATE":  2,
}

func (x GetRequest_DataType) String() string {
	return proto.EnumName(GetRequest_DataType_name, int32(x))
}

func (GetRequest_DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{2, 0}
}

type LoadToCandidateRequest_LoadType int32

const (
	// Merge the data tree into the candidate configuration.
	LoadToCandidateRequest_MERGE LoadToCandidateRequest_LoadType = 0
	// Replace the candidate configuration by the provided data tree.
	LoadToCandidateRequest_REPLACE LoadToCandidateRequest_LoadType = 1
)

var LoadToCandidateRequest_LoadType_name = map[int32]string{
	0: "MERGE",
	1: "REPLACE",
}

var LoadToCandidateRequest_LoadType_value = map[string]int32{
	"MERGE":   0,
	"REPLACE": 1,
}

func (x LoadToCandidateRequest_LoadType) String() string {
	return proto.EnumName(LoadToCandidateRequest_LoadType_name, int32(x))
}

func (LoadToCandidateRequest_LoadType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{12, 0}
}

type CommitRequest_Phase int32

const (
	// Validate if the configuration changes are valid (phase 0).
	CommitRequest_VALIDATE CommitRequest_Phase = 0
	// Prepare resources to apply the configuration changes (phase 1).
	CommitRequest_PREPARE CommitRequest_Phase = 1
	// Release previously allocated resources (phase 2).
	CommitRequest_ABORT CommitRequest_Phase = 2
	// Apply the configuration changes (phase 2).
	CommitRequest_APPLY CommitRequest_Phase = 3
	// All of the above (VALIDATE + PREPARE + ABORT/APPLY).
	//
	// This option can't be used to implement network-wide transactions,
	// since they require the manager entity to take into account the results
	// of the preparation phase of multiple managed devices.
	CommitRequest_ALL CommitRequest_Phase = 4
)

var CommitRequest_Phase_name = map[int32]string{
	0: "VALIDATE",
	1: "PREPARE",
	2: "ABORT",
	3: "APPLY",
	4: "ALL",
}

var CommitRequest_Phase_value = map[string]int32{
	"VALIDATE": 0,
	"PREPARE":  1,
	"ABORT":    2,
	"APPLY":    3,
	"ALL":      4,
}

func (x CommitRequest_Phase) String() string {
	return proto.EnumName(CommitRequest_Phase_name, int32(x))
}

func (CommitRequest_Phase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{14, 0}
}

//
// RPC: GetCapabilities()
//
type GetCapabilitiesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCapabilitiesRequest) Reset()         { *m = GetCapabilitiesRequest{} }
func (m *GetCapabilitiesRequest) String() string { return proto.CompactTextString(m) }
func (*GetCapabilitiesRequest) ProtoMessage()    {}
func (*GetCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{0}
}

func (m *GetCapabilitiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCapabilitiesRequest.Unmarshal(m, b)
}
func (m *GetCapabilitiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCapabilitiesRequest.Marshal(b, m, deterministic)
}
func (m *GetCapabilitiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCapabilitiesRequest.Merge(m, src)
}
func (m *GetCapabilitiesRequest) XXX_Size() int {
	return xxx_messageInfo_GetCapabilitiesRequest.Size(m)
}
func (m *GetCapabilitiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCapabilitiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCapabilitiesRequest proto.InternalMessageInfo

type GetCapabilitiesResponse struct {
	// FRR version.
	FrrVersion string `protobuf:"bytes,1,opt,name=frr_version,json=frrVersion,proto3" json:"frr_version,omitempty"`
	// Indicates whether FRR was compiled with support for configuration
	// rollbacks or not (--enable-config-rollbacks).
	RollbackSupport bool `protobuf:"varint,2,opt,name=rollback_support,json=rollbackSupport,proto3" json:"rollback_support,omitempty"`
	// Supported schema modules.
	SupportedModules []*ModuleData `protobuf:"bytes,3,rep,name=supported_modules,json=supportedModules,proto3" json:"supported_modules,omitempty"`
	// Supported encodings.
	SupportedEncodings   []Encoding `protobuf:"varint,4,rep,packed,name=supported_encodings,json=supportedEncodings,proto3,enum=frr.Encoding" json:"supported_encodings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetCapabilitiesResponse) Reset()         { *m = GetCapabilitiesResponse{} }
func (m *GetCapabilitiesResponse) String() string { return proto.CompactTextString(m) }
func (*GetCapabilitiesResponse) ProtoMessage()    {}
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{1}
}

func (m *GetCapabilitiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCapabilitiesResponse.Unmarshal(m, b)
}
func (m *GetCapabilitiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCapabilitiesResponse.Marshal(b, m, deterministic)
}
func (m *GetCapabilitiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCapabilitiesResponse.Merge(m, src)
}
func (m *GetCapabilitiesResponse) XXX_Size() int {
	return xxx_messageInfo_GetCapabilitiesResponse.Size(m)
}
func (m *GetCapabilitiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCapabilitiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCapabilitiesResponse proto.InternalMessageInfo

func (m *GetCapabilitiesResponse) GetFrrVersion() string {
	if m != nil {
		return m.FrrVersion
	}
	return ""
}

func (m *GetCapabilitiesResponse) GetRollbackSupport() bool {
	if m != nil {
		return m.RollbackSupport
	}
	return false
}

func (m *GetCapabilitiesResponse) GetSupportedModules() []*ModuleData {
	if m != nil {
		return m.SupportedModules
	}
	return nil
}

func (m *GetCapabilitiesResponse) GetSupportedEncodings() []Encoding {
	if m != nil {
		return m.SupportedEncodings
	}
	return nil
}

//
// RPC: Get()
//
type GetRequest struct {
	// The type of data being requested.
	Type GetRequest_DataType `protobuf:"varint,1,opt,name=type,proto3,enum=frr.GetRequest_DataType" json:"type,omitempty"`
	// Encoding to be used.
	Encoding Encoding `protobuf:"varint,2,opt,name=encoding,proto3,enum=frr.Encoding" json:"encoding,omitempty"`
	// Include implicit default nodes.
	WithDefaults bool `protobuf:"varint,3,opt,name=with_defaults,json=withDefaults,proto3" json:"with_defaults,omitempty"`
	// Paths requested by the client.
	Path                 []string `protobuf:"bytes,4,rep,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetType() GetRequest_DataType {
	if m != nil {
		return m.Type
	}
	return GetRequest_ALL
}

func (m *GetRequest) GetEncoding() Encoding {
	if m != nil {
		return m.Encoding
	}
	return Encoding_JSON
}

func (m *GetRequest) GetWithDefaults() bool {
	if m != nil {
		return m.WithDefaults
	}
	return false
}

func (m *GetRequest) GetPath() []string {
	if m != nil {
		return m.Path
	}
	return nil
}

type GetResponse struct {
	// Timestamp in nanoseconds since Epoch.
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The requested data.
	Data                 *DataTree `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{3}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetResponse) GetData() *DataTree {
	if m != nil {
		return m.Data
	}
	return nil
}

//
// RPC: CreateCandidate()
//
type CreateCandidateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCandidateRequest) Reset()         { *m = CreateCandidateRequest{} }
func (m *CreateCandidateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCandidateRequest) ProtoMessage()    {}
func (*CreateCandidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{4}
}

func (m *CreateCandidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCandidateRequest.Unmarshal(m, b)
}
func (m *CreateCandidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCandidateRequest.Marshal(b, m, deterministic)
}
func (m *CreateCandidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCandidateRequest.Merge(m, src)
}
func (m *CreateCandidateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCandidateRequest.Size(m)
}
func (m *CreateCandidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCandidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCandidateRequest proto.InternalMessageInfo

type CreateCandidateResponse struct {
	// Handle to the new created candidate configuration.
	CandidateId          uint32   `protobuf:"varint,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCandidateResponse) Reset()         { *m = CreateCandidateResponse{} }
func (m *CreateCandidateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCandidateResponse) ProtoMessage()    {}
func (*CreateCandidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{5}
}

func (m *CreateCandidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCandidateResponse.Unmarshal(m, b)
}
func (m *CreateCandidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCandidateResponse.Marshal(b, m, deterministic)
}
func (m *CreateCandidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCandidateResponse.Merge(m, src)
}
func (m *CreateCandidateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCandidateResponse.Size(m)
}
func (m *CreateCandidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCandidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCandidateResponse proto.InternalMessageInfo

func (m *CreateCandidateResponse) GetCandidateId() uint32 {
	if m != nil {
		return m.CandidateId
	}
	return 0
}

//
// RPC: DeleteCandidate()
//
type DeleteCandidateRequest struct {
	// Candidate configuration to delete.
	CandidateId          uint32   `protobuf:"varint,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCandidateRequest) Reset()         { *m = DeleteCandidateRequest{} }
func (m *DeleteCandidateRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCandidateRequest) ProtoMessage()    {}
func (*DeleteCandidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{6}
}

func (m *DeleteCandidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCandidateRequest.Unmarshal(m, b)
}
func (m *DeleteCandidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCandidateRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCandidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCandidateRequest.Merge(m, src)
}
func (m *DeleteCandidateRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCandidateRequest.Size(m)
}
func (m *DeleteCandidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCandidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCandidateRequest proto.InternalMessageInfo

func (m *DeleteCandidateRequest) GetCandidateId() uint32 {
	if m != nil {
		return m.CandidateId
	}
	return 0
}

type DeleteCandidateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCandidateResponse) Reset()         { *m = DeleteCandidateResponse{} }
func (m *DeleteCandidateResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCandidateResponse) ProtoMessage()    {}
func (*DeleteCandidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{7}
}

func (m *DeleteCandidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCandidateResponse.Unmarshal(m, b)
}
func (m *DeleteCandidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCandidateResponse.Marshal(b, m, deterministic)
}
func (m *DeleteCandidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCandidateResponse.Merge(m, src)
}
func (m *DeleteCandidateResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCandidateResponse.Size(m)
}
func (m *DeleteCandidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCandidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCandidateResponse proto.InternalMessageInfo

//
// RPC: UpdateCandidate()
//
type UpdateCandidateRequest struct {
	// Candidate configuration to update.
	CandidateId          uint32   `protobuf:"varint,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCandidateRequest) Reset()         { *m = UpdateCandidateRequest{} }
func (m *UpdateCandidateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCandidateRequest) ProtoMessage()    {}
func (*UpdateCandidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{8}
}

func (m *UpdateCandidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCandidateRequest.Unmarshal(m, b)
}
func (m *UpdateCandidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCandidateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCandidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCandidateRequest.Merge(m, src)
}
func (m *UpdateCandidateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCandidateRequest.Size(m)
}
func (m *UpdateCandidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCandidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCandidateRequest proto.InternalMessageInfo

func (m *UpdateCandidateRequest) GetCandidateId() uint32 {
	if m != nil {
		return m.CandidateId
	}
	return 0
}

type UpdateCandidateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCandidateResponse) Reset()         { *m = UpdateCandidateResponse{} }
func (m *UpdateCandidateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCandidateResponse) ProtoMessage()    {}
func (*UpdateCandidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{9}
}

func (m *UpdateCandidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCandidateResponse.Unmarshal(m, b)
}
func (m *UpdateCandidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCandidateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCandidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCandidateResponse.Merge(m, src)
}
func (m *UpdateCandidateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCandidateResponse.Size(m)
}
func (m *UpdateCandidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCandidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCandidateResponse proto.InternalMessageInfo

//
// RPC: EditCandidate()
//
type EditCandidateRequest struct {
	// Candidate configuration that is going to be edited.
	CandidateId uint32 `protobuf:"varint,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	// Data elements to be created or updated.
	Update []*PathValue `protobuf:"bytes,2,rep,name=update,proto3" json:"update,omitempty"`
	// Paths to be deleted from the data tree.
	Delete               []*PathValue `protobuf:"bytes,3,rep,name=delete,proto3" json:"delete,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EditCandidateRequest) Reset()         { *m = EditCandidateRequest{} }
func (m *EditCandidateRequest) String() string { return proto.CompactTextString(m) }
func (*EditCandidateRequest) ProtoMessage()    {}
func (*EditCandidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{10}
}

func (m *EditCandidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditCandidateRequest.Unmarshal(m, b)
}
func (m *EditCandidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditCandidateRequest.Marshal(b, m, deterministic)
}
func (m *EditCandidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditCandidateRequest.Merge(m, src)
}
func (m *EditCandidateRequest) XXX_Size() int {
	return xxx_messageInfo_EditCandidateRequest.Size(m)
}
func (m *EditCandidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditCandidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditCandidateRequest proto.InternalMessageInfo

func (m *EditCandidateRequest) GetCandidateId() uint32 {
	if m != nil {
		return m.CandidateId
	}
	return 0
}

func (m *EditCandidateRequest) GetUpdate() []*PathValue {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *EditCandidateRequest) GetDelete() []*PathValue {
	if m != nil {
		return m.Delete
	}
	return nil
}

type EditCandidateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditCandidateResponse) Reset()         { *m = EditCandidateResponse{} }
func (m *EditCandidateResponse) String() string { return proto.CompactTextString(m) }
func (*EditCandidateResponse) ProtoMessage()    {}
func (*EditCandidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{11}
}

func (m *EditCandidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditCandidateResponse.Unmarshal(m, b)
}
func (m *EditCandidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditCandidateResponse.Marshal(b, m, deterministic)
}
func (m *EditCandidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditCandidateResponse.Merge(m, src)
}
func (m *EditCandidateResponse) XXX_Size() int {
	return xxx_messageInfo_EditCandidateResponse.Size(m)
}
func (m *EditCandidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditCandidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditCandidateResponse proto.InternalMessageInfo

//
// RPC: LoadToCandidate()
//
type LoadToCandidateRequest struct {
	// Candidate configuration that is going to be edited.
	CandidateId uint32 `protobuf:"varint,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	// Load operation to apply.
	Type LoadToCandidateRequest_LoadType `protobuf:"varint,2,opt,name=type,proto3,enum=frr.LoadToCandidateRequest_LoadType" json:"type,omitempty"`
	// Configuration data.
	Config               *DataTree `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LoadToCandidateRequest) Reset()         { *m = LoadToCandidateRequest{} }
func (m *LoadToCandidateRequest) String() string { return proto.CompactTextString(m) }
func (*LoadToCandidateRequest) ProtoMessage()    {}
func (*LoadToCandidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{12}
}

func (m *LoadToCandidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadToCandidateRequest.Unmarshal(m, b)
}
func (m *LoadToCandidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadToCandidateRequest.Marshal(b, m, deterministic)
}
func (m *LoadToCandidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadToCandidateRequest.Merge(m, src)
}
func (m *LoadToCandidateRequest) XXX_Size() int {
	return xxx_messageInfo_LoadToCandidateRequest.Size(m)
}
func (m *LoadToCandidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadToCandidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadToCandidateRequest proto.InternalMessageInfo

func (m *LoadToCandidateRequest) GetCandidateId() uint32 {
	if m != nil {
		return m.CandidateId
	}
	return 0
}

func (m *LoadToCandidateRequest) GetType() LoadToCandidateRequest_LoadType {
	if m != nil {
		return m.Type
	}
	return LoadToCandidateRequest_MERGE
}

func (m *LoadToCandidateRequest) GetConfig() *DataTree {
	if m != nil {
		return m.Config
	}
	return nil
}

type LoadToCandidateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadToCandidateResponse) Reset()         { *m = LoadToCandidateResponse{} }
func (m *LoadToCandidateResponse) String() string { return proto.CompactTextString(m) }
func (*LoadToCandidateResponse) ProtoMessage()    {}
func (*LoadToCandidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{13}
}

func (m *LoadToCandidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadToCandidateResponse.Unmarshal(m, b)
}
func (m *LoadToCandidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadToCandidateResponse.Marshal(b, m, deterministic)
}
func (m *LoadToCandidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadToCandidateResponse.Merge(m, src)
}
func (m *LoadToCandidateResponse) XXX_Size() int {
	return xxx_messageInfo_LoadToCandidateResponse.Size(m)
}
func (m *LoadToCandidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadToCandidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadToCandidateResponse proto.InternalMessageInfo

//
// RPC: Commit()
//
type CommitRequest struct {
	// Candidate configuration that is going to be committed.
	CandidateId uint32 `protobuf:"varint,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	// Transaction phase.
	Phase CommitRequest_Phase `protobuf:"varint,2,opt,name=phase,proto3,enum=frr.CommitRequest_Phase" json:"phase,omitempty"`
	// Assign a comment to this commit.
	Comment              string   `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitRequest) Reset()         { *m = CommitRequest{} }
func (m *CommitRequest) String() string { return proto.CompactTextString(m) }
func (*CommitRequest) ProtoMessage()    {}
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{14}
}

func (m *CommitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitRequest.Unmarshal(m, b)
}
func (m *CommitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitRequest.Marshal(b, m, deterministic)
}
func (m *CommitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitRequest.Merge(m, src)
}
func (m *CommitRequest) XXX_Size() int {
	return xxx_messageInfo_CommitRequest.Size(m)
}
func (m *CommitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitRequest proto.InternalMessageInfo

func (m *CommitRequest) GetCandidateId() uint32 {
	if m != nil {
		return m.CandidateId
	}
	return 0
}

func (m *CommitRequest) GetPhase() CommitRequest_Phase {
	if m != nil {
		return m.Phase
	}
	return CommitRequest_VALIDATE
}

func (m *CommitRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type CommitResponse struct {
	// ID of the created configuration transaction (when the phase is APPLY
	// or ALL).
	TransactionId        uint32   `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitResponse) Reset()         { *m = CommitResponse{} }
func (m *CommitResponse) String() string { return proto.CompactTextString(m) }
func (*CommitResponse) ProtoMessage()    {}
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{15}
}

func (m *CommitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitResponse.Unmarshal(m, b)
}
func (m *CommitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitResponse.Marshal(b, m, deterministic)
}
func (m *CommitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitResponse.Merge(m, src)
}
func (m *CommitResponse) XXX_Size() int {
	return xxx_messageInfo_CommitResponse.Size(m)
}
func (m *CommitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommitResponse proto.InternalMessageInfo

func (m *CommitResponse) GetTransactionId() uint32 {
	if m != nil {
		return m.TransactionId
	}
	return 0
}

//
// RPC: ListTransactions()
//
type ListTransactionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTransactionsRequest) Reset()         { *m = ListTransactionsRequest{} }
func (m *ListTransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListTransactionsRequest) ProtoMessage()    {}
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{16}
}

func (m *ListTransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTransactionsRequest.Unmarshal(m, b)
}
func (m *ListTransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTransactionsRequest.Marshal(b, m, deterministic)
}
func (m *ListTransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTransactionsRequest.Merge(m, src)
}
func (m *ListTransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListTransactionsRequest.Size(m)
}
func (m *ListTransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTransactionsRequest proto.InternalMessageInfo

type ListTransactionsResponse struct {
	// Transaction ID.
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Client that committed the transaction.
	Client string `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	// Date and time the transaction was committed.
	Date string `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	// Comment assigned to the transaction.
	Comment              string   `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTransactionsResponse) Reset()         { *m = ListTransactionsResponse{} }
func (m *ListTransactionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListTransactionsResponse) ProtoMessage()    {}
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{17}
}

func (m *ListTransactionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTransactionsResponse.Unmarshal(m, b)
}
func (m *ListTransactionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTransactionsResponse.Marshal(b, m, deterministic)
}
func (m *ListTransactionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTransactionsResponse.Merge(m, src)
}
func (m *ListTransactionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListTransactionsResponse.Size(m)
}
func (m *ListTransactionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTransactionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTransactionsResponse proto.InternalMessageInfo

func (m *ListTransactionsResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ListTransactionsResponse) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func (m *ListTransactionsResponse) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *ListTransactionsResponse) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

//
// RPC: GetTransaction()
//
type GetTransactionRequest struct {
	// Transaction to retrieve.
	TransactionId uint32 `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// Encoding to be used.
	Encoding Encoding `protobuf:"varint,2,opt,name=encoding,proto3,enum=frr.Encoding" json:"encoding,omitempty"`
	// Include implicit default nodes.
	WithDefaults         bool     `protobuf:"varint,3,opt,name=with_defaults,json=withDefaults,proto3" json:"with_defaults,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionRequest) Reset()         { *m = GetTransactionRequest{} }
func (m *GetTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionRequest) ProtoMessage()    {}
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{18}
}

func (m *GetTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionRequest.Unmarshal(m, b)
}
func (m *GetTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionRequest.Marshal(b, m, deterministic)
}
func (m *GetTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionRequest.Merge(m, src)
}
func (m *GetTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransactionRequest.Size(m)
}
func (m *GetTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionRequest proto.InternalMessageInfo

func (m *GetTransactionRequest) GetTransactionId() uint32 {
	if m != nil {
		return m.TransactionId
	}
	return 0
}

func (m *GetTransactionRequest) GetEncoding() Encoding {
	if m != nil {
		return m.Encoding
	}
	return Encoding_JSON
}

func (m *GetTransactionRequest) GetWithDefaults() bool {
	if m != nil {
		return m.WithDefaults
	}
	return false
}

type GetTransactionResponse struct {
	Config               *DataTree `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetTransactionResponse) Reset()         { *m = GetTransactionResponse{} }
func (m *GetTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*GetTransactionResponse) ProtoMessage()    {}
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{19}
}

func (m *GetTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionResponse.Unmarshal(m, b)
}
func (m *GetTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionResponse.Marshal(b, m, deterministic)
}
func (m *GetTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionResponse.Merge(m, src)
}
func (m *GetTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_GetTransactionResponse.Size(m)
}
func (m *GetTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionResponse proto.InternalMessageInfo

func (m *GetTransactionResponse) GetConfig() *DataTree {
	if m != nil {
		return m.Config
	}
	return nil
}

//
// RPC: LockConfig()
//
type LockConfigRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockConfigRequest) Reset()         { *m = LockConfigRequest{} }
func (m *LockConfigRequest) String() string { return proto.CompactTextString(m) }
func (*LockConfigRequest) ProtoMessage()    {}
func (*LockConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{20}
}

func (m *LockConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockConfigRequest.Unmarshal(m, b)
}
func (m *LockConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockConfigRequest.Marshal(b, m, deterministic)
}
func (m *LockConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockConfigRequest.Merge(m, src)
}
func (m *LockConfigRequest) XXX_Size() int {
	return xxx_messageInfo_LockConfigRequest.Size(m)
}
func (m *LockConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LockConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LockConfigRequest proto.InternalMessageInfo

type LockConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockConfigResponse) Reset()         { *m = LockConfigResponse{} }
func (m *LockConfigResponse) String() string { return proto.CompactTextString(m) }
func (*LockConfigResponse) ProtoMessage()    {}
func (*LockConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{21}
}

func (m *LockConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockConfigResponse.Unmarshal(m, b)
}
func (m *LockConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockConfigResponse.Marshal(b, m, deterministic)
}
func (m *LockConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockConfigResponse.Merge(m, src)
}
func (m *LockConfigResponse) XXX_Size() int {
	return xxx_messageInfo_LockConfigResponse.Size(m)
}
func (m *LockConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LockConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LockConfigResponse proto.InternalMessageInfo

//
// RPC: UnlockConfig()
//
type UnlockConfigRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlockConfigRequest) Reset()         { *m = UnlockConfigRequest{} }
func (m *UnlockConfigRequest) String() string { return proto.CompactTextString(m) }
func (*UnlockConfigRequest) ProtoMessage()    {}
func (*UnlockConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{22}
}

func (m *UnlockConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockConfigRequest.Unmarshal(m, b)
}
func (m *UnlockConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockConfigRequest.Marshal(b, m, deterministic)
}
func (m *UnlockConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockConfigRequest.Merge(m, src)
}
func (m *UnlockConfigRequest) XXX_Size() int {
	return xxx_messageInfo_UnlockConfigRequest.Size(m)
}
func (m *UnlockConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockConfigRequest proto.InternalMessageInfo

type UnlockConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlockConfigResponse) Reset()         { *m = UnlockConfigResponse{} }
func (m *UnlockConfigResponse) String() string { return proto.CompactTextString(m) }
func (*UnlockConfigResponse) ProtoMessage()    {}
func (*UnlockConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{23}
}

func (m *UnlockConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockConfigResponse.Unmarshal(m, b)
}
func (m *UnlockConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockConfigResponse.Marshal(b, m, deterministic)
}
func (m *UnlockConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockConfigResponse.Merge(m, src)
}
func (m *UnlockConfigResponse) XXX_Size() int {
	return xxx_messageInfo_UnlockConfigResponse.Size(m)
}
func (m *UnlockConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockConfigResponse proto.InternalMessageInfo

//
// RPC: Execute()
//
type ExecuteRequest struct {
	// Path of the YANG RPC or YANG Action.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Input parameters.
	Input                []*PathValue `protobuf:"bytes,2,rep,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ExecuteRequest) Reset()         { *m = ExecuteRequest{} }
func (m *ExecuteRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteRequest) ProtoMessage()    {}
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{24}
}

func (m *ExecuteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteRequest.Unmarshal(m, b)
}
func (m *ExecuteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteRequest.Merge(m, src)
}
func (m *ExecuteRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteRequest.Size(m)
}
func (m *ExecuteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteRequest proto.InternalMessageInfo

func (m *ExecuteRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ExecuteRequest) GetInput() []*PathValue {
	if m != nil {
		return m.Input
	}
	return nil
}

type ExecuteResponse struct {
	// Output parameters.
	Output               []*PathValue `protobuf:"bytes,1,rep,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ExecuteResponse) Reset()         { *m = ExecuteResponse{} }
func (m *ExecuteResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteResponse) ProtoMessage()    {}
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{25}
}

func (m *ExecuteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteResponse.Unmarshal(m, b)
}
func (m *ExecuteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteResponse.Merge(m, src)
}
func (m *ExecuteResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteResponse.Size(m)
}
func (m *ExecuteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteResponse proto.InternalMessageInfo

func (m *ExecuteResponse) GetOutput() []*PathValue {
	if m != nil {
		return m.Output
	}
	return nil
}

// YANG module.
type ModuleData struct {
	// Name of the YANG module;
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Organization publishing the module.
	Organization string `protobuf:"bytes,2,opt,name=organization,proto3" json:"organization,omitempty"`
	// Latest revision of the module;
	Revision             string   `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleData) Reset()         { *m = ModuleData{} }
func (m *ModuleData) String() string { return proto.CompactTextString(m) }
func (*ModuleData) ProtoMessage()    {}
func (*ModuleData) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{26}
}

func (m *ModuleData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleData.Unmarshal(m, b)
}
func (m *ModuleData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleData.Marshal(b, m, deterministic)
}
func (m *ModuleData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleData.Merge(m, src)
}
func (m *ModuleData) XXX_Size() int {
	return xxx_messageInfo_ModuleData.Size(m)
}
func (m *ModuleData) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleData.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleData proto.InternalMessageInfo

func (m *ModuleData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModuleData) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *ModuleData) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

// Path-value pair representing a data element.
type PathValue struct {
	// YANG data path.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Data value.
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PathValue) Reset()         { *m = PathValue{} }
func (m *PathValue) String() string { return proto.CompactTextString(m) }
func (*PathValue) ProtoMessage()    {}
func (*PathValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{27}
}

func (m *PathValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PathValue.Unmarshal(m, b)
}
func (m *PathValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PathValue.Marshal(b, m, deterministic)
}
func (m *PathValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PathValue.Merge(m, src)
}
func (m *PathValue) XXX_Size() int {
	return xxx_messageInfo_PathValue.Size(m)
}
func (m *PathValue) XXX_DiscardUnknown() {
	xxx_messageInfo_PathValue.DiscardUnknown(m)
}

var xxx_messageInfo_PathValue proto.InternalMessageInfo

func (m *PathValue) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *PathValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// YANG instance data.
type DataTree struct {
	Encoding             Encoding `protobuf:"varint,1,opt,name=encoding,proto3,enum=frr.Encoding" json:"encoding,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataTree) Reset()         { *m = DataTree{} }
func (m *DataTree) String() string { return proto.CompactTextString(m) }
func (*DataTree) ProtoMessage()    {}
func (*DataTree) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c2b24b5b63befd3, []int{28}
}

func (m *DataTree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataTree.Unmarshal(m, b)
}
func (m *DataTree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataTree.Marshal(b, m, deterministic)
}
func (m *DataTree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataTree.Merge(m, src)
}
func (m *DataTree) XXX_Size() int {
	return xxx_messageInfo_DataTree.Size(m)
}
func (m *DataTree) XXX_DiscardUnknown() {
	xxx_messageInfo_DataTree.DiscardUnknown(m)
}

var xxx_messageInfo_DataTree proto.InternalMessageInfo

func (m *DataTree) GetEncoding() Encoding {
	if m != nil {
		return m.Encoding
	}
	return Encoding_JSON
}

func (m *DataTree) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterEnum("frr.Encoding", Encoding_name, Encoding_value)
	proto.RegisterEnum("frr.GetRequest_DataType", GetRequest_DataType_name, GetRequest_DataType_value)
	proto.RegisterEnum("frr.LoadToCandidateRequest_LoadType", LoadToCandidateRequest_LoadType_name, LoadToCandidateRequest_LoadType_value)
	proto.RegisterEnum("frr.CommitRequest_Phase", CommitRequest_Phase_name, CommitRequest_Phase_value)
	proto.RegisterType((*GetCapabilitiesRequest)(nil), "frr.GetCapabilitiesRequest")
	proto.RegisterType((*GetCapabilitiesResponse)(nil), "frr.GetCapabilitiesResponse")
	proto.RegisterType((*GetRequest)(nil), "frr.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "frr.GetResponse")
	proto.RegisterType((*CreateCandidateRequest)(nil), "frr.CreateCandidateRequest")
	proto.RegisterType((*CreateCandidateResponse)(nil), "frr.CreateCandidateResponse")
	proto.RegisterType((*DeleteCandidateRequest)(nil), "frr.DeleteCandidateRequest")
	proto.RegisterType((*DeleteCandidateResponse)(nil), "frr.DeleteCandidateResponse")
	proto.RegisterType((*UpdateCandidateRequest)(nil), "frr.UpdateCandidateRequest")
	proto.RegisterType((*UpdateCandidateResponse)(nil), "frr.UpdateCandidateResponse")
	proto.RegisterType((*EditCandidateRequest)(nil), "frr.EditCandidateRequest")
	proto.RegisterType((*EditCandidateResponse)(nil), "frr.EditCandidateResponse")
	proto.RegisterType((*LoadToCandidateRequest)(nil), "frr.LoadToCandidateRequest")
	proto.RegisterType((*LoadToCandidateResponse)(nil), "frr.LoadToCandidateResponse")
	proto.RegisterType((*CommitRequest)(nil), "frr.CommitRequest")
	proto.RegisterType((*CommitResponse)(nil), "frr.CommitResponse")
	proto.RegisterType((*ListTransactionsRequest)(nil), "frr.ListTransactionsRequest")
	proto.RegisterType((*ListTransactionsResponse)(nil), "frr.ListTransactionsResponse")
	proto.RegisterType((*GetTransactionRequest)(nil), "frr.GetTransactionRequest")
	proto.RegisterType((*GetTransactionResponse)(nil), "frr.GetTransactionResponse")
	proto.RegisterType((*LockConfigRequest)(nil), "frr.LockConfigRequest")
	proto.RegisterType((*LockConfigResponse)(nil), "frr.LockConfigResponse")
	proto.RegisterType((*UnlockConfigRequest)(nil), "frr.UnlockConfigRequest")
	proto.RegisterType((*UnlockConfigResponse)(nil), "frr.UnlockConfigResponse")
	proto.RegisterType((*ExecuteRequest)(nil), "frr.ExecuteRequest")
	proto.RegisterType((*ExecuteResponse)(nil), "frr.ExecuteResponse")
	proto.RegisterType((*ModuleData)(nil), "frr.ModuleData")
	proto.RegisterType((*PathValue)(nil), "frr.PathValue")
	proto.RegisterType((*DataTree)(nil), "frr.DataTree")
}

func init() { proto.RegisterFile("frr-northbound.proto", fileDescriptor_9c2b24b5b63befd3) }

var fileDescriptor_9c2b24b5b63befd3 = []byte{
	// 1155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xed, 0x6e, 0xda, 0x56,
	0x18, 0xc6, 0x40, 0x08, 0xbc, 0x04, 0xe2, 0x9e, 0x10, 0x42, 0xdc, 0x56, 0x4b, 0xbd, 0xb6, 0x4a,
	0xab, 0x0e, 0x4d, 0xa9, 0xf6, 0xa5, 0x55, 0xab, 0x18, 0xf1, 0x58, 0x3a, 0x92, 0x20, 0x87, 0x46,
	0xdb, 0xaf, 0xec, 0x04, 0x1f, 0x12, 0xab, 0x60, 0x7b, 0xf6, 0x21, 0x5b, 0x77, 0x07, 0xfb, 0xb3,
	0x1b, 0xd9, 0x45, 0x6c, 0xbf, 0x77, 0x1b, 0xbb, 0x91, 0xe9, 0x7c, 0x19, 0x8c, 0x4d, 0xd5, 0x45,
	0xfb, 0x67, 0x3f, 0xef, 0xf7, 0xf1, 0x73, 0xde, 0x07, 0xa0, 0x31, 0x0e, 0xc3, 0x8f, 0x3c, 0x3f,
	0xa4, 0xd7, 0x97, 0xfe, 0xcc, 0x73, 0xda, 0x41, 0xe8, 0x53, 0x1f, 0x15, 0xc6, 0x61, 0x68, 0xb6,
	0xa0, 0xd9, 0x23, 0xb4, 0x8b, 0x03, 0x7c, 0xe9, 0x4e, 0x5c, 0xea, 0x92, 0xc8, 0x26, 0x3f, 0xcd,
	0x48, 0x44, 0xcd, 0x7f, 0x34, 0xd8, 0x49, 0x99, 0xa2, 0xc0, 0xf7, 0x22, 0x82, 0x3e, 0x80, 0xea,
	0x38, 0x0c, 0x2f, 0x6e, 0x48, 0x18, 0xb9, 0xbe, 0xd7, 0xd2, 0xf6, 0xb4, 0xfd, 0x8a, 0x0d, 0xe3,
	0x30, 0x3c, 0x17, 0x08, 0x7a, 0x02, 0x7a, 0xe8, 0x4f, 0x26, 0x97, 0x78, 0xf4, 0xe6, 0x22, 0x9a,
	0x05, 0x81, 0x1f, 0xd2, 0x56, 0x7e, 0x4f, 0xdb, 0x2f, 0xdb, 0x9b, 0x0a, 0x3f, 0x13, 0x30, 0x7a,
	0x01, 0x77, 0xa4, 0x07, 0x71, 0x2e, 0xa6, 0xbe, 0x33, 0x9b, 0x90, 0xa8, 0x55, 0xd8, 0x2b, 0xec,
	0x57, 0x0f, 0x36, 0xdb, 0xe3, 0x30, 0x6c, 0x1f, 0x73, 0xec, 0x10, 0x53, 0x6c, 0xeb, 0xb1, 0xa7,
	0x00, 0x23, 0xf4, 0x15, 0x6c, 0xcd, 0xa3, 0x89, 0x37, 0xf2, 0x1d, 0xd7, 0xbb, 0x8a, 0x5a, 0xc5,
	0xbd, 0xc2, 0x7e, 0xfd, 0xa0, 0xc6, 0xe3, 0x2d, 0x89, 0xda, 0x28, 0xf6, 0x54, 0x50, 0x64, 0xfe,
	0xad, 0x01, 0xf4, 0x08, 0x95, 0x43, 0xa3, 0x67, 0x50, 0xa4, 0x6f, 0x03, 0xc2, 0x27, 0xaa, 0x1f,
	0xb4, 0x78, 0xfc, 0xdc, 0xdc, 0x66, 0x4d, 0x0c, 0xdf, 0x06, 0xc4, 0xe6, 0x5e, 0xe8, 0x09, 0x94,
	0x55, 0x49, 0x3e, 0x5d, 0xaa, 0x62, 0x6c, 0x46, 0x1f, 0x42, 0xed, 0x67, 0x97, 0x5e, 0x5f, 0x38,
	0x64, 0x8c, 0x67, 0x13, 0xca, 0x26, 0x64, 0xa7, 0xb1, 0xc1, 0xc0, 0x43, 0x89, 0x21, 0x04, 0xc5,
	0x00, 0xd3, 0x6b, 0xde, 0x7d, 0xc5, 0xe6, 0xcf, 0xe6, 0x53, 0x28, 0xab, 0xaa, 0x68, 0x1d, 0x0a,
	0x9d, 0x7e, 0x5f, 0xcf, 0x21, 0x80, 0x52, 0xf7, 0xf4, 0xe4, 0x9b, 0xa3, 0x9e, 0xae, 0xa1, 0x0a,
	0xac, 0x9d, 0x0d, 0x3b, 0x43, 0x4b, 0xcf, 0x9b, 0x27, 0x50, 0xe5, 0xcd, 0xca, 0xaf, 0x74, 0x0f,
	0x2a, 0xd4, 0x9d, 0x92, 0x88, 0xe2, 0x69, 0xc0, 0x27, 0x2a, 0xd8, 0x73, 0x00, 0x3d, 0x80, 0xa2,
	0x83, 0x29, 0xe6, 0x8d, 0x57, 0x65, 0xe3, 0xbc, 0x52, 0x48, 0x88, 0xcd, 0x4d, 0x8c, 0x1c, 0xdd,
	0x90, 0x60, 0x4a, 0xba, 0xd8, 0x73, 0x5c, 0x07, 0x53, 0xa2, 0xc8, 0xf1, 0x02, 0x76, 0x52, 0x16,
	0x59, 0xf5, 0x01, 0x6c, 0x8c, 0x14, 0x78, 0xe1, 0x3a, 0xbc, 0x70, 0xcd, 0xae, 0xc6, 0xd8, 0x91,
	0x63, 0x7e, 0x09, 0xcd, 0x43, 0x32, 0x21, 0xe9, 0xbc, 0xef, 0x13, 0xbc, 0x0b, 0x3b, 0xa9, 0x60,
	0x51, 0x9a, 0xe5, 0x7d, 0x1d, 0x38, 0xf8, 0xd6, 0x79, 0x53, 0xc1, 0x32, 0xef, 0x6f, 0x1a, 0x34,
	0x2c, 0xc7, 0xa5, 0xb7, 0x48, 0x8b, 0x1e, 0x43, 0x69, 0xc6, 0xd3, 0xb6, 0xf2, 0x9c, 0xd3, 0x75,
	0x7e, 0xd0, 0x03, 0x4c, 0xaf, 0xcf, 0xf1, 0x64, 0x46, 0x6c, 0x69, 0x65, 0x7e, 0x0e, 0x1f, 0x4b,
	0x72, 0x3f, 0xe5, 0x27, 0xac, 0xe6, 0x0e, 0x6c, 0x2f, 0xb5, 0x22, 0x9b, 0xfc, 0x4b, 0x83, 0x66,
	0xdf, 0xc7, 0xce, 0xd0, 0xbf, 0x4d, 0x9b, 0x9f, 0x4b, 0xe2, 0x0b, 0x1a, 0x3f, 0xe4, 0xc5, 0xb3,
	0xb3, 0x09, 0x78, 0x7e, 0x09, 0x1e, 0x41, 0x69, 0xe4, 0x7b, 0x63, 0xf7, 0x8a, 0x53, 0x3a, 0xc5,
	0x24, 0x69, 0x34, 0x4d, 0x28, 0xab, 0x40, 0x46, 0xd9, 0x63, 0xcb, 0xee, 0x59, 0x7a, 0x0e, 0x55,
	0x61, 0xdd, 0xb6, 0x06, 0xfd, 0x4e, 0xd7, 0xd2, 0x35, 0xf6, 0x09, 0x52, 0x35, 0xe5, 0x74, 0x7f,
	0x6a, 0x50, 0xeb, 0xfa, 0xd3, 0xa9, 0x4b, 0xff, 0xc3, 0x50, 0x6d, 0x58, 0x0b, 0xae, 0x71, 0xa4,
	0xa6, 0x12, 0xd7, 0x39, 0x91, 0xa5, 0x3d, 0x60, 0x76, 0x5b, 0xb8, 0xa1, 0x16, 0xac, 0x8f, 0xfc,
	0xe9, 0x94, 0x78, 0x94, 0xcf, 0x52, 0xb1, 0xd5, 0xab, 0xd9, 0x81, 0x35, 0xee, 0x89, 0x36, 0xa0,
	0x7c, 0xde, 0xe9, 0x1f, 0x1d, 0xb2, 0x0b, 0xc7, 0xbb, 0x1f, 0xd8, 0xd6, 0xa0, 0x63, 0x5b, 0xe2,
	0x22, 0x76, 0xbe, 0x3e, 0xb5, 0x87, 0x7a, 0x9e, 0x3f, 0x0e, 0x06, 0xfd, 0x1f, 0xf4, 0x82, 0xba,
	0xb3, 0x45, 0xf3, 0x33, 0xa8, 0xab, 0xd2, 0xf2, 0xa6, 0x3c, 0x82, 0x3a, 0x0d, 0xb1, 0x17, 0xe1,
	0x11, 0x75, 0x7d, 0x6f, 0x3e, 0x43, 0x6d, 0x01, 0x15, 0xc4, 0xec, 0xbb, 0x11, 0x1d, 0xce, 0xc1,
	0x78, 0x47, 0x07, 0xd0, 0x4a, 0x9b, 0x64, 0xf6, 0x3a, 0xe4, 0xe3, 0x8c, 0x79, 0xd7, 0x41, 0x4d,
	0x28, 0x8d, 0x26, 0x2e, 0x9b, 0x2d, 0xcf, 0x67, 0x93, 0x6f, 0x6c, 0xe9, 0x70, 0x7a, 0x8a, 0x89,
	0xf9, 0xf3, 0xe2, 0x41, 0x14, 0x93, 0x07, 0xf1, 0xbb, 0x06, 0xdb, 0x3d, 0xb2, 0x58, 0x51, 0x7d,
	0x8f, 0xf7, 0x9b, 0xe6, 0xff, 0xde, 0x99, 0xe6, 0x4b, 0x2e, 0x60, 0x89, 0x7e, 0xe2, 0xe3, 0x55,
	0xc4, 0xd4, 0xde, 0x45, 0xcc, 0x2d, 0xb8, 0xd3, 0xf7, 0x47, 0x6f, 0xba, 0xfc, 0x4d, 0x1d, 0x6c,
	0x03, 0xd0, 0x22, 0x28, 0x49, 0xb8, 0x0d, 0x5b, 0xaf, 0xbd, 0x49, 0xca, 0xb9, 0x09, 0x8d, 0x24,
	0x2c, 0xdd, 0x5f, 0x41, 0xdd, 0xfa, 0x85, 0x8c, 0x66, 0xf3, 0x8b, 0xa8, 0x16, 0xbc, 0x10, 0x4c,
	0xfe, 0x8c, 0x1e, 0xc2, 0x9a, 0xeb, 0x05, 0x33, 0xba, 0x62, 0x3f, 0x08, 0xa3, 0xf9, 0x05, 0x6c,
	0xc6, 0xb9, 0xe4, 0x7c, 0x8f, 0xa1, 0xe4, 0xcf, 0x28, 0x8b, 0xd4, 0xb2, 0x37, 0x86, 0xb0, 0x9a,
	0x3f, 0x02, 0xcc, 0x25, 0x94, 0xb5, 0xe0, 0xe1, 0x29, 0x51, 0x2d, 0xb0, 0x67, 0x64, 0xc2, 0x86,
	0x1f, 0x5e, 0x61, 0xcf, 0xfd, 0x15, 0xb3, 0x13, 0x94, 0x04, 0x49, 0x60, 0xc8, 0x80, 0x72, 0x48,
	0x6e, 0x5c, 0xae, 0xf7, 0x82, 0x2a, 0xf1, 0xbb, 0xf9, 0x09, 0x54, 0xe2, 0xb2, 0x99, 0x33, 0x36,
	0x60, 0xed, 0x86, 0x19, 0x65, 0x66, 0xf1, 0x62, 0x1e, 0x49, 0x69, 0x0b, 0x49, 0x52, 0x4a, 0xb5,
	0x77, 0xd3, 0x02, 0x2d, 0x08, 0x97, 0x20, 0x2c, 0x7e, 0x7a, 0x1f, 0xca, 0xca, 0x13, 0x95, 0xa1,
	0xf8, 0xea, 0xec, 0xf4, 0x44, 0xcf, 0xb1, 0xbb, 0xf7, 0xfd, 0x71, 0x5f, 0xd7, 0x0e, 0xfe, 0x58,
	0x07, 0x38, 0x89, 0x7f, 0xff, 0xa0, 0x13, 0xd8, 0x5c, 0xfa, 0x65, 0x83, 0xee, 0x2a, 0xa9, 0xcf,
	0xf8, 0x29, 0x64, 0xdc, 0xcb, 0x36, 0xca, 0xcf, 0x9c, 0x43, 0xcf, 0xa0, 0xd0, 0x23, 0x14, 0x6d,
	0x2e, 0xfd, 0x5c, 0x30, 0xf4, 0x39, 0xa0, 0x7c, 0x3f, 0xd6, 0x58, 0xf5, 0x25, 0xed, 0x94, 0xd5,
	0xb3, 0xb5, 0x56, 0x56, 0x5f, 0x21, 0xb7, 0x66, 0x8e, 0xe5, 0x5b, 0x12, 0x44, 0x99, 0x2f, 0x5b,
	0x63, 0x65, 0xbe, 0x55, 0x1a, 0xca, 0xf3, 0x2d, 0x09, 0xa1, 0xcc, 0x97, 0xad, 0xad, 0x32, 0xdf,
	0x2a, 0xed, 0xcc, 0xa1, 0x6f, 0xa1, 0x96, 0x50, 0x2c, 0xb4, 0x2b, 0xbe, 0x6c, 0x86, 0xa0, 0x1a,
	0x46, 0x96, 0x69, 0xb1, 0xb3, 0x25, 0x7d, 0x90, 0x9d, 0x65, 0x2b, 0x95, 0xec, 0x6c, 0x95, 0xa4,
	0xe4, 0xd0, 0x73, 0x28, 0x89, 0x95, 0x8c, 0x50, 0x5a, 0x1a, 0x8c, 0xad, 0x04, 0x16, 0x07, 0x9d,
	0x81, 0xbe, 0xbc, 0x73, 0x91, 0x2c, 0x94, 0xbd, 0xa5, 0x8d, 0xfb, 0x2b, 0xac, 0x0b, 0x9c, 0xf8,
	0x0e, 0xea, 0xc9, 0x2d, 0x86, 0x0c, 0xc5, 0x9d, 0xf4, 0xaa, 0x35, 0xee, 0x66, 0xda, 0xe2, 0x0e,
	0x5f, 0x02, 0xcc, 0x97, 0x17, 0x6a, 0xca, 0x43, 0x58, 0xda, 0x5a, 0xc6, 0x4e, 0x0a, 0x8f, 0x13,
	0x58, 0xb0, 0xb1, 0xb8, 0xd0, 0x90, 0x10, 0xce, 0x8c, 0xd5, 0x67, 0xec, 0x66, 0x58, 0xe2, 0x34,
	0x9f, 0xc2, 0xba, 0xdc, 0x59, 0x48, 0x9c, 0x65, 0x72, 0x1b, 0x1a, 0x8d, 0x24, 0xa8, 0xe2, 0x2e,
	0x4b, 0xfc, 0xff, 0xc9, 0xf3, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x48, 0xd1, 0xed, 0x7c, 0xb7,
	0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NorthboundClient is the client API for Northbound service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NorthboundClient interface {
	// Retrieve the capabilities supported by the target.
	GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error)
	// Retrieve configuration data, state data or both from the target.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (Northbound_GetClient, error)
	// Create a new candidate configuration and return a reference to it. The
	// created candidate is a copy of the running configuration.
	CreateCandidate(ctx context.Context, in *CreateCandidateRequest, opts ...grpc.CallOption) (*CreateCandidateResponse, error)
	// Delete a candidate configuration.
	DeleteCandidate(ctx context.Context, in *DeleteCandidateRequest, opts ...grpc.CallOption) (*DeleteCandidateResponse, error)
	// Update a candidate configuration by rebasing the changes on top of the
	// latest running configuration. Resolve conflicts automatically by giving
	// preference to the changes done in the candidate configuration.
	UpdateCandidate(ctx context.Context, in *UpdateCandidateRequest, opts ...grpc.CallOption) (*UpdateCandidateResponse, error)
	// Edit a candidate configuration. All changes are discarded if any error
	// happens.
	EditCandidate(ctx context.Context, in *EditCandidateRequest, opts ...grpc.CallOption) (*EditCandidateResponse, error)
	// Load configuration data into a candidate configuration. Both merge and
	// replace semantics are supported.
	LoadToCandidate(ctx context.Context, in *LoadToCandidateRequest, opts ...grpc.CallOption) (*LoadToCandidateResponse, error)
	// Create a new configuration transaction using a two-phase commit protocol.
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	// List the metadata of all configuration transactions recorded in the
	// transactions database.
	ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (Northbound_ListTransactionsClient, error)
	// Fetch a configuration (identified by its transaction ID) from the
	// transactions database.
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error)
	// Lock the running configuration, preventing other users from changing it.
	LockConfig(ctx context.Context, in *LockConfigRequest, opts ...grpc.CallOption) (*LockConfigResponse, error)
	// Unlock the running configuration.
	UnlockConfig(ctx context.Context, in *UnlockConfigRequest, opts ...grpc.CallOption) (*UnlockConfigResponse, error)
	// Execute a YANG RPC.
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
}

type northboundClient struct {
	cc grpc.ClientConnInterface
}

func NewNorthboundClient(cc grpc.ClientConnInterface) NorthboundClient {
	return &northboundClient{cc}
}

func (c *northboundClient) GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error) {
	out := new(GetCapabilitiesResponse)
	err := c.cc.Invoke(ctx, "/frr.Northbound/GetCapabilities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *northboundClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (Northbound_GetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Northbound_serviceDesc.Streams[0], "/frr.Northbound/Get", opts...)
	if err != nil {
		return nil, err
	}
	x := &northboundGetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Northbound_GetClient interface {
	Recv() (*GetResponse, error)
	grpc.ClientStream
}

type northboundGetClient struct {
	grpc.ClientStream
}

func (x *northboundGetClient) Recv() (*GetResponse, error) {
	m := new(GetResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *northboundClient) CreateCandidate(ctx context.Context, in *CreateCandidateRequest, opts ...grpc.CallOption) (*CreateCandidateResponse, error) {
	out := new(CreateCandidateResponse)
	err := c.cc.Invoke(ctx, "/frr.Northbound/CreateCandidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *northboundClient) DeleteCandidate(ctx context.Context, in *DeleteCandidateRequest, opts ...grpc.CallOption) (*DeleteCandidateResponse, error) {
	out := new(DeleteCandidateResponse)
	err := c.cc.Invoke(ctx, "/frr.Northbound/DeleteCandidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *northboundClient) UpdateCandidate(ctx context.Context, in *UpdateCandidateRequest, opts ...grpc.CallOption) (*UpdateCandidateResponse, error) {
	out := new(UpdateCandidateResponse)
	err := c.cc.Invoke(ctx, "/frr.Northbound/UpdateCandidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *northboundClient) EditCandidate(ctx context.Context, in *EditCandidateRequest, opts ...grpc.CallOption) (*EditCandidateResponse, error) {
	out := new(EditCandidateResponse)
	err := c.cc.Invoke(ctx, "/frr.Northbound/EditCandidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *northboundClient) LoadToCandidate(ctx context.Context, in *LoadToCandidateRequest, opts ...grpc.CallOption) (*LoadToCandidateResponse, error) {
	out := new(LoadToCandidateResponse)
	err := c.cc.Invoke(ctx, "/frr.Northbound/LoadToCandidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *northboundClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, "/frr.Northbound/Commit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *northboundClient) ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (Northbound_ListTransactionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Northbound_serviceDesc.Streams[1], "/frr.Northbound/ListTransactions", opts...)
	if err != nil {
		return nil, err
	}
	x := &northboundListTransactionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Northbound_ListTransactionsClient interface {
	Recv() (*ListTransactionsResponse, error)
	grpc.ClientStream
}

type northboundListTransactionsClient struct {
	grpc.ClientStream
}

func (x *northboundListTransactionsClient) Recv() (*ListTransactionsResponse, error) {
	m := new(ListTransactionsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *northboundClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error) {
	out := new(GetTransactionResponse)
	err := c.cc.Invoke(ctx, "/frr.Northbound/GetTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *northboundClient) LockConfig(ctx context.Context, in *LockConfigRequest, opts ...grpc.CallOption) (*LockConfigResponse, error) {
	out := new(LockConfigResponse)
	err := c.cc.Invoke(ctx, "/frr.Northbound/LockConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *northboundClient) UnlockConfig(ctx context.Context, in *UnlockConfigRequest, opts ...grpc.CallOption) (*UnlockConfigResponse, error) {
	out := new(UnlockConfigResponse)
	err := c.cc.Invoke(ctx, "/frr.Northbound/UnlockConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *northboundClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, "/frr.Northbound/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NorthboundServer is the server API for Northbound service.
type NorthboundServer interface {
	// Retrieve the capabilities supported by the target.
	GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error)
	// Retrieve configuration data, state data or both from the target.
	Get(*GetRequest, Northbound_GetServer) error
	// Create a new candidate configuration and return a reference to it. The
	// created candidate is a copy of the running configuration.
	CreateCandidate(context.Context, *CreateCandidateRequest) (*CreateCandidateResponse, error)
	// Delete a candidate configuration.
	DeleteCandidate(context.Context, *DeleteCandidateRequest) (*DeleteCandidateResponse, error)
	// Update a candidate configuration by rebasing the changes on top of the
	// latest running configuration. Resolve conflicts automatically by giving
	// preference to the changes done in the candidate configuration.
	UpdateCandidate(context.Context, *UpdateCandidateRequest) (*UpdateCandidateResponse, error)
	// Edit a candidate configuration. All changes are discarded if any error
	// happens.
	EditCandidate(context.Context, *EditCandidateRequest) (*EditCandidateResponse, error)
	// Load configuration data into a candidate configuration. Both merge and
	// replace semantics are supported.
	LoadToCandidate(context.Context, *LoadToCandidateRequest) (*LoadToCandidateResponse, error)
	// Create a new configuration transaction using a two-phase commit protocol.
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	// List the metadata of all configuration transactions recorded in the
	// transactions database.
	ListTransactions(*ListTransactionsRequest, Northbound_ListTransactionsServer) error
	// Fetch a configuration (identified by its transaction ID) from the
	// transactions database.
	GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error)
	// Lock the running configuration, preventing other users from changing it.
	LockConfig(context.Context, *LockConfigRequest) (*LockConfigResponse, error)
	// Unlock the running configuration.
	UnlockConfig(context.Context, *UnlockConfigRequest) (*UnlockConfigResponse, error)
	// Execute a YANG RPC.
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
}

// UnimplementedNorthboundServer can be embedded to have forward compatible implementations.
type UnimplementedNorthboundServer struct {
}

func (*UnimplementedNorthboundServer) GetCapabilities(ctx context.Context, req *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (*UnimplementedNorthboundServer) Get(req *GetRequest, srv Northbound_GetServer) error {
	return status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedNorthboundServer) CreateCandidate(ctx context.Context, req *CreateCandidateRequest) (*CreateCandidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCandidate not implemented")
}
func (*UnimplementedNorthboundServer) DeleteCandidate(ctx context.Context, req *DeleteCandidateRequest) (*DeleteCandidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCandidate not implemented")
}
func (*UnimplementedNorthboundServer) UpdateCandidate(ctx context.Context, req *UpdateCandidateRequest) (*UpdateCandidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCandidate not implemented")
}
func (*UnimplementedNorthboundServer) EditCandidate(ctx context.Context, req *EditCandidateRequest) (*EditCandidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditCandidate not implemented")
}
func (*UnimplementedNorthboundServer) LoadToCandidate(ctx context.Context, req *LoadToCandidateRequest) (*LoadToCandidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadToCandidate not implemented")
}
func (*UnimplementedNorthboundServer) Commit(ctx context.Context, req *CommitRequest) (*CommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (*UnimplementedNorthboundServer) ListTransactions(req *ListTransactionsRequest, srv Northbound_ListTransactionsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListTransactions not implemented")
}
func (*UnimplementedNorthboundServer) GetTransaction(ctx context.Context, req *GetTransactionRequest) (*GetTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (*UnimplementedNorthboundServer) LockConfig(ctx context.Context, req *LockConfigRequest) (*LockConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockConfig not implemented")
}
func (*UnimplementedNorthboundServer) UnlockConfig(ctx context.Context, req *UnlockConfigRequest) (*UnlockConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlockConfig not implemented")
}
func (*UnimplementedNorthboundServer) Execute(ctx context.Context, req *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}

func RegisterNorthboundServer(s *grpc.Server, srv NorthboundServer) {
	s.RegisterService(&_Northbound_serviceDesc, srv)
}

func _Northbound_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorthboundServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frr.Northbound/GetCapabilities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorthboundServer).GetCapabilities(ctx, req.(*GetCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Northbound_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NorthboundServer).Get(m, &northboundGetServer{stream})
}

type Northbound_GetServer interface {
	Send(*GetResponse) error
	grpc.ServerStream
}

type northboundGetServer struct {
	grpc.ServerStream
}

func (x *northboundGetServer) Send(m *GetResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Northbound_CreateCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorthboundServer).CreateCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frr.Northbound/CreateCandidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorthboundServer).CreateCandidate(ctx, req.(*CreateCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Northbound_DeleteCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorthboundServer).DeleteCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frr.Northbound/DeleteCandidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorthboundServer).DeleteCandidate(ctx, req.(*DeleteCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Northbound_UpdateCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorthboundServer).UpdateCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frr.Northbound/UpdateCandidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorthboundServer).UpdateCandidate(ctx, req.(*UpdateCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Northbound_EditCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorthboundServer).EditCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frr.Northbound/EditCandidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorthboundServer).EditCandidate(ctx, req.(*EditCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Northbound_LoadToCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadToCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorthboundServer).LoadToCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frr.Northbound/LoadToCandidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorthboundServer).LoadToCandidate(ctx, req.(*LoadToCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Northbound_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorthboundServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frr.Northbound/Commit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorthboundServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Northbound_ListTransactions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListTransactionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NorthboundServer).ListTransactions(m, &northboundListTransactionsServer{stream})
}

type Northbound_ListTransactionsServer interface {
	Send(*ListTransactionsResponse) error
	grpc.ServerStream
}

type northboundListTransactionsServer struct {
	grpc.ServerStream
}

func (x *northboundListTransactionsServer) Send(m *ListTransactionsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Northbound_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorthboundServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frr.Northbound/GetTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorthboundServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Northbound_LockConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorthboundServer).LockConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frr.Northbound/LockConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorthboundServer).LockConfig(ctx, req.(*LockConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Northbound_UnlockConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorthboundServer).UnlockConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frr.Northbound/UnlockConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorthboundServer).UnlockConfig(ctx, req.(*UnlockConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Northbound_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NorthboundServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frr.Northbound/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NorthboundServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Northbound_serviceDesc = grpc.ServiceDesc{
	ServiceName: "frr.Northbound",
	HandlerType: (*NorthboundServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _Northbound_GetCapabilities_Handler,
		},
		{
			MethodName: "CreateCandidate",
			Handler:    _Northbound_CreateCandidate_Handler,
		},
		{
			MethodName: "DeleteCandidate",
			Handler:    _Northbound_DeleteCandidate_Handler,
		},
		{
			MethodName: "UpdateCandidate",
			Handler:    _Northbound_UpdateCandidate_Handler,
		},
		{
			MethodName: "EditCandidate",
			Handler:    _Northbound_EditCandidate_Handler,
		},
		{
			MethodName: "LoadToCandidate",
			Handler:    _Northbound_LoadToCandidate_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _Northbound_Commit_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _Northbound_GetTransaction_Handler,
		},
		{
			MethodName: "LockConfig",
			Handler:    _Northbound_LockConfig_Handler,
		},
		{
			MethodName: "UnlockConfig",
			Handler:    _Northbound_UnlockConfig_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _Northbound_Execute_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Get",
			Handler:       _Northbound_Get_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListTransactions",
			Handler:       _Northbound_ListTransactions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "frr-northbound.proto",
}
